### PR TITLE
Fix examples

### LINKED ISSUE #15: Galgebra not able to print some products and inverses of multivectors
Dear all,

Galgebra does not seem to be able to print out quantities such as the following:
Products (inner, left contraction, right contraction or geometric) of a (multi)vector with itself, e.g., a * a. It should be noted that the product of a vector with a different one is OK, e.g., a * b is printed out correctly.
By the same token, no inverse of an invertible multi(vector) is printed out.
It looks as if squares of the components of (multi)vectors were the culprits, as these appear in the above calculations.

Python (3.4 and 3.7):
The computer hangs. Here’s a print screen
“
C:\Users\Freddy\Desktop\Python\programs>C:\Python34-37\python "spacetimePython3.py"
latex file = spacetimePython3.tex
pdflatex path = C:\Program Files\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe
“

Here’s the message returned to the console after exiting with a ctrl-C:
“
Traceback (most recent call last):
  File "spacetimePython3.py", line 65, in <module>
    xpdf(paper=(8,9),crop=True)
  File "C:\Python34-37\lib\site-packages\galgebra\printer.py", line 1165, in xpdf
    os.system(latex_str + ' ' + filename[:-4] + sys_cmd['null'])
KeyboardInterrupt
Terminate batch job (Y/N)?
“

I tried IPython (notebook), i.e. Jupyter (with both browsers, viz., Firefox and Chrome).
In this case, the unevaluated latex code is returned and the computer does not hang.

Is there any workaround available?

Kind regards,
Freddy Baudine

### LINKED ISSUE #18: TypeError: unicode argument expected, got 'str'
As reported by @FreddyBaudine  [here](https://github.com/pygae/galgebra/issues/15#issuecomment-468553015) and discussed [here](https://github.com/pygae/galgebra/issues/15#issuecomment-468888295), it seems that the usages of `StringIO` should be replaced by `BytesIO`.

The work needs to be done:

- [ ] Reproduce by tests: possibly a `test_py2_compat.py` since most tests are written in Python 3 flavor
- [ ] Identify the root cause and best practice
- [ ] Fix it and pass tests

### LINKED ISSUE #26: Christoffel symbols of the first kind ill calculated - Calculation of the Christoffel symbols of the second kind returns an error
Dear All,

Galgebra does not seem to obtain the correct Christoffel symbols of the first kind; at least the values printed out indicate a skew symmetry, which is strange.

Starting with the metric tensor relating to a two dimensional manifold,  the unit sphere, viz., 
image
galgebra yields the following components for the Christoffel symbols of the first kind, 
image
when, in fact, the correct values are
image
As is well known, these symbols are symmetrical in the indices alpha and beta.

As for the Christoffel symbols of the second kind they are not calculated, an error is returned instead:
“
C:\Users\Freddy\Desktop\Issues\Christoffel>C:\Anaconda3\python "Christoffel_symbols_checking.py"
Traceback (most recent call last):
  File "Christoffel_symbols_checking.py", line 47, in <module>
    Cf2 = sp2.Christoffel_symbols(mode=2)
  File "C:\Anaconda3\lib\site-packages\galgebra\metric.py", line 490, in Christoffel_symbols
    Gamma_ijk += Gijl * self.g(l,)
TypeError: 'MutableDenseMatrix' object is not callable

C:\Users\Freddy\Desktop\Issues\Christoffel>pause
Press any key to continue . . .
“
It is not at all clear how the differential operators can be properly computed  (see zip file enclosed)
 when it is explicitly stated in Section 2.3.1 of Galgebra: a Geometric Algebra Module for Sympy (October 8, 2016) that the Christoffel symbols of the first kind are made use of to perform a number of calculations, notably to obtain the derivatives of the basis vectors (footnote on page 17). Unless the Christoffel symbols are not actually used at all! This would explain that, but I can be totally wrong on this.

Look forward to receiving any views on all this.
Kind regards,
FB
freddy.baudine@outlook.com
[Christoffel.zip](https://github.com/pygae/galgebra/files/2988943/Christoffel.zip)

### LINKED ISSUE #27: class MV is now broken
Due to my commit [Remove circular dependencies](https://github.com/pygae/galgebra/commit/2838a1cd0cfd9360ee8bd41469739c6b6769930f) , module `mv` no longer depends on module `ga`, but currently MV still lives in `mv` and calls `ga`.

So any examples using class MV, particularly the ones in `examples/Old Format` won't work and that includes some references to class MV in the new README. (My mistake......)

I have no intention to reintroduce circular dependencies or to drop support for class MV, so here's the work needed to be done:

- [x] Create a new module that depends on `ga` and `mv` to put class MV and possibly the widely used `com()`, could name it `legacy` or `deprecated` (related to a17995707df2a1f6cc88ddb37b6479f0bfd3ce82)
- [x] Fix any references to class MV in README or doc
- [x] Fix examples using class MV

### LINKED ISSUE #29: Sometimes plain text is printed with or instead of LaTeX in Jupyter Notebooks
Sometimes plain text is printed with or instead of LaTeX in Jupyter Notebooks.

The "with" case:

In https://nbviewer.jupyter.org/github/pygae/galgebra/blob/15-print-pow/examples/ipython/verify_doc_python.ipynb:

image

The "instead of" case:

In https://nbviewer.jupyter.org/github/pygae/galgebra/blob/15-print-pow/examples/ipython/simple_ga_test.ipynb : 

image

### LINKED ISSUE #30: galgebra doesn't fully support using LaTeX as symbol name
If use something like

```python
symbols(r'{\color{airforceblue}\theta} {\color{applegreen}\phi}', real = True)
```

will produce invalid LaTeX output caused by double escaping:

```
! Missing } inserted.
<inserted text>
                }
l.61 ...\ 0 & {\sin{\left ({\color{airforceblue}\\
                                                  theta } \right )}}^{2}  \e...
```

If use something like

```python
symbols(r'{\color{airforceblue}theta} {\color{applegreen}phi}', real = True)
```

to avoid double escaping, then the result is partially `theta`/`phi` and partially `\theta`/`\phi`:

image

The expected result is:

image

### LINKED ISSUE #32: Reciprocal basis and inverse metric for non-orthogonal basis
The calculation of reciprocal basis for non-orthogonal basis in GAlgebra deviate from standard definition and caused a bug when calculating inverse metric.

See https://nbviewer.jupyter.org/github/utensil/julia-playground/blob/master/py/galgebra_reciprocal_basis.ipynb for step-by-step investigation.

### PR DESCRIPTION
**Pull request by utensil**
In GAlgebra 0.4.3, the first version claims to support Python 3, most of the examples are actually not working under both Python 2.7 and 3. All the examples needs to be convert to a format that's compatible with both Python 2.7 and 3, add them to CI to verify them, and fix bugs (it turns out that I've introduced quite a few of them when converting GAlgebra to support Python 3) along the way.

Here's the work needed to be done:

- [x] Fix `examples/Terminal` and verify them in CI
- [x] Fix `examples/LaTeX` and verify them in CI
- [x] Fix #27  
- [x] Fix `examples/Old Format` and verify them in CI
- [x] Gather all examples that run in CI to `examples/ipython`
- [x] Fix #15 
- [x] Fix #18
- [x] Fix #26 
- [x] Add Circle CI
- [x] Fix for Python 3.4-3.7
- [x] Fix #29
- [x] Fix #30
- [x] Change the name to better describe the PR
- [x] Fix #32
- [x] Implement a part of #25
- [x] Add other Python 3 versions to CI (by using CircleCI)
- [x] Add CodeCov to Circle CI and remove TravisCI build for PRs
- [x] Add doc describing freezing dep to SymPy 1.3, see #31 
- [x] Write README.md for `test` and `examples`

It's also part of #3 .

DISCLAIMER: 

This PR only make sure the example can be executed and give exactly the same output under Python 2.7 and 3 (that is actually 3.6, the only Python 3 version that CI runs against but when all these work are finished, I'll add all the Python 3 version that is supported by sympy, namely 3.4, 3.5, 3.6 and 3.7).

This PR does not include the efforts to make sure all the math is sound, that's a lot of manual work, and is not practical due to my time constraint. It can be done after this PR is merged.

### CODE REVIEW

**Comment by utensil** [comment]
@FreddyBaudine Please check out https://nbviewer.jupyter.org/github/pygae/galgebra/blob/15-print-pow/examples/ipython/st4.ipynb to see whether the LaTeX output is expected and the math is sound.

**Comment by FreddyBaudine** [comment]
Dear Utensil,

The LateX output is OK albeit a bit different from Alan Bromborsky’s, in that the quantities to be squared are not parenthesised first.  But at any rate, no confusion is possible between powers and superscripts.

As for the maths, as far as I can tell, they are OK.

Speaking of mathematics, a couple of years back, I had an email exchange with Alan Bromborsky about his intention to develop the ‘Split Differential Operator’ in view of implementing a general ‘Dot’ notation for differential  operators, as  described in his Galgebra: a Geometric Algebra for Sympy. This device is used a great deal in the book after Chris Doran and Anthony Lasenby, Geometric Algebra for Physicists. In those days it had not yet been implemented.  
He said that he was used to writing the doc first, then program. I trust his duties must have prevented him from completing his great work.
Is there a chance of having it implemented in a future release?

Many thanks for your help.

Kind regards,
Freddy Baudine

**Comment by utensil** [comment]
> The LateX output is OK albeit a bit different from Alan Bromborsky’s, in that the quantities to be squared are not parenthesised first. But at any rate, no confusion is possible between powers and superscripts.

You mean the LaTex source by "parenthesised"( i.e. braces ) , right? Are the math outputs identical too?

LaTeX doesn't accept consecutive superscripts, so no braces is not an valid syntax. And for the semantics, the superscripts are merely indices and part of the base of the power, so it makes sense for the function name and superscripts  to be in a brace for the ^ to understand them as a whole base.

So I don't see a way around this without the verbosity of braces although I think there could be a smart way to figure out whether there are superscripts or subscripts for the function so the LaTex source could be more succinct for plain functions. But the recursive nature of printing implementation make it hard to predict all the scenarios of `_print`ing a function so it's simpler and safer to wrap them in braces in both cases for now.

**Comment by utensil** [comment]
> Speaking of mathematics, a couple of years back, I had an email exchange with Alan Bromborsky about his intention to develop the ‘Split Differential Operator’ in view of implementing a general ‘Dot’ notation for differential operators, as described in his Galgebra: a Geometric Algebra for Sympy. This device is used a great deal in the book after Chris Doran and Anthony Lasenby, Geometric Algebra for Physicists. In those days it had not yet been implemented.
> He said that he was used to writing the doc first, then program. I trust his duties must have prevented him from completing his great work.
> Is there a chance of having it implemented in a future release?

I've open an issue for this and let's discuss it further there.

**Comment by FreddyBaudine** [comment]
Dear Utensil,

I owe you an apology for I am afraid I ill-expressed myself. In my comment above, when I compared Alan Bromborsky’s output and yours, I had in mind what is actually printed out in the PDF files not the LateX side. 
To wit, the following example.
Bromborsky’ output
image
Your output
image

In your version, the actual powers are placed a little higher than the indices, hence no confusion is possible.

At any rate, the fact that (in the PDF file) components of multivectors that have to be squared are not enclosed in parentheses makes for more compact formulae.

Kind regards,
Freddy Baudine

**Comment by utensil** [comment]
Oh I see, although it's more compact without the parenthesis but it's much more clear with the parenthesis? Let me see how this relates to the original implementation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by utensil** [comment]
In https://github.com/sympy/sympy/blob/sympy-0.7.6.1/sympy/printing/latex.py#L173 there seems to be a mechanism to determine whether to add parenthesis.

**Comment by utensil** [comment]
I would like to further examine the best way to fix this. The current fix could be considered as a usable one but there's plenty room to be improved.

**Comment by utensil** [comment]
It seems `_print_Pow` has a pretty good test coverage and easy to make it 100%: https://codecov.io/gh/pygae/galgebra/src/15-print-pow/galgebra/printer.py#L644

**Comment by utensil** [comment]
Interesting, galgebra is not coloring the bases in terminal on Travis, investigating......

**Comment by utensil** [comment]
> Merging [#17](https://codecov.io/gh/pygae/galgebra/pull/17?src=pr&el=desc) into [master](https://codecov.io/gh/pygae/galgebra/commit/b5e46d28fe4d2c1cf7a64615377d90d2a0907310?src=pr&el=desc) will **increase** coverage by `17.31%`.
> The diff coverage is `90.69%`.

I'm glad that this PR has increased coverage  by `17.31%` and reached 66.45%.

The price is the much longer time for CI. It took 2 min to run all tests for master but 10+ min for this PR.

There're indeed duplicated tests, but they are run for different outputs: plain text, ANSI Console, Jupyter Notebook LaTeX, full LaTeX file for `pdflatex` etc. There could be a way to remove such duplication to reduce CI time but it can be done in a later PR.

**Comment by utensil** [comment]
This PR is almost ready, but before reviewing, I still wish to:

- [ ] Write README.md for `test` and `examples`
- [ ] Possibly add README for examples to main doc
- [ ] Check whether to fix examples in `doc/python`
- [ ] Possibly reflect some of the changes to doc or fix errors in doc related to this PR

**Comment by utensil** [comment]
@hugohadfield @arsenovic This PR is finally finished and ready for review.

Sorry during the process of fixing the examples, I end up opening many new issues and fixing them, and this PR has become very big and takes 3 months to finish. I can't exactly break them into smaller PRs since the commits are now strongly connected. All of these make it very difficult to review.

So here's my suggestion for how to review:

- the main thread listed all the tasks of this PR, 19 of them, please first review these tasks
- https://github.com/pygae/galgebra/pull/17#issuecomment-479485792 listed some of the tasks left for future PRs
- I've properly documented the changes in this PR in multiple README.md files, please search `README.md` in the diff, namely (ordered by importance)
  - README.md
  - test/README.md
  - examples/README.md
  - doc/books/Macdonald/README.md
  - examples/Macdonald/README.md
  - doc/README.md

**Comment by utensil** [comment]
This is ready to merge and I'll make a new release based on it.

I think I'll be working on the following features in 0.4.5:

1. Performance: GAlgebra is extremely slow for certain coordinates and metrics, primarily caused by eagerness in the calculus stuff and simplification, so the main idea is laziness, so higher dimensions can be supported
2. Better support for FGA and CGA: it's already partially supported but I need to extensively verify them and some complications are expected
3. SymPy 1.4 support: I need to reimplement `collect` in SymPy for non-commutative symbols, that's quite some work, see https://github.com/pygae/galgebra/issues/31
4. Doc improvements: I want to write a true tutorial, weaving the examples together; also the docstring in Python code are mostly ill formated;
5. Examples fixing: examples in `doc/python` are not verified; some of them have serious correctness issues yet to be fixed.

**Pull request merged**
