### PR TITLE
Add a CI build for SymPy master

### LINKED ISSUE #94: Add a CI build for SymPy master
See https://github.com/pygae/galgebra/issues/31#issuecomment-535826866 and https://github.com/sympy/sympy/issues/8365#issuecomment-61387644 .

### PR DESCRIPTION
**Pull request by utensil**
Fixes #94

### CODE REVIEW

**Comment by eric-wieser** [comment]
```
e new experience. The majority of our users find it easier to fix failing builds. 
Opt In
Jobspygaegalgebra sympy_master_ci 3580 (python-3.8-sympy-master)
Rerun workflow
FAILED
Finished:
3 hr ago (04:44)
Previous:
3579
Parallelism:
1x out of 0x
Queued:
05:08 waiting + 00:02 in queue
Resources:
2CPU/4096MB
Workflow:
build
Context:
N/A
Triggered by:
Utensil Song (pushed e03f0a4)
PR:
#289
COMMITS (1)
Utensil SongGitHube03f0a4Add a CI build for SymPy master
Test Summary (1)
Configuration
Timing
Parameters

PYTEST
1 FAILURE
Your job ran 294 tests with 1 failure
Cell 19 - examples.ipython.dop.ipynb
examples/ipython/dop.ipynb
#x1B[91mNotebook cell execution failed#x1B[0m
#x1B[94mCell 19: Cell outputs differ

Input:
#x1B[0mF.norm()

#x1B[94mTraceback:#x1B[0m
#x1B[94m mismatch 'text/latex'#x1B[91m

 assert reference_output == test_output failed:

  '$\\sqrt{\\op...i \\right)}}$' == '$\\sqrt{\\le...i \\right)}}$'
  - $\sqrt{\left(\operatorname{F^{\phi}}\right)^{2}{\left(r,\theta,\phi \right)} + \left(\operatorname{F^{r}}\right)^{2}{\left(r,\theta,\phi \right)} + \left(\operatorname{F^{\theta}}\right)^{2}{\left(r,\theta,\phi \right)}}$
  ?        ------                       -------                                    ------                    -------                                    ------                         -------
  + $\sqrt{\operatorname{F^{\phi}}^{2}{\left(r,\theta,\phi \right)} + \operatorname{F^{r}}^{2}{\left(r,\theta,\phi \right)} + \operatorname{F^{\theta}}^{2}{\left(r,\theta,\phi \right)}}$
#x1B[0m
```

**Comment by utensil** [comment]
The expected (old) output is:

```tex
\displaystyle \sqrt{\operatorname{F^{\phi}}^{2}{\left(r,\theta,\phi \right)} + \operatorname{F^{r}}^{2}{\left(r,\theta,\phi \right)} + \operatorname{F^{\theta}}^{2}{\left(r,\theta,\phi \right)}}
```

**Comment by utensil** [comment]
Seems related to sympy/sympy#18256

**Comment by eric-wieser** [comment]
Odd, it seems to me that `galgebra.printer` already has a special-case for this, so I'm surprised we were caught out by that.

**Comment by utensil** [comment]
The behavior seems to be introduced earlier in sympy/sympy#17288 .

**Comment by utensil** [comment]
B.T.W. It's obvious to me that it should not `parenthesize_super` in this case.

**Comment by eric-wieser** [comment]
Here's the code I'm thinking of:

https://github.com/pygae/galgebra/blob/f1ea1b76e62fe58b9b64a451f198bc93d079f320/galgebra/printer.py#L782-L800

**Comment by utensil** [comment]
I would like to allow the CI against sympy master to fail, but CircleCI doesn't seem to support so (googled `allow_fail`, `optional` etc.)

**Comment by eric-wieser** [comment]
Unforunately it seems there's no way to conditionally skip a test with `nbval` either.

**Comment by eric-wieser** [comment]
For now, can you just add another section to `.nbval_sanitize.cfg` to allow that discrepancy?

**Comment by utensil** [comment]
> Here's the code I'm thinking of

Some tests show `_print_Function` is not executed for that case(i.e. `F.norm()`) and its type is actually `sympy.core.power.Pow`.

**Comment by eric-wieser** [comment]
Perhaps `exp` is no longer passed to print_function by sympy master

**Pull request merged**
