### PR TITLE
Remove special-cases for scalars in contractions

### PR DESCRIPTION
**Pull request by eric-wieser**
It's possible this will be marginally slower, but it makes everything much easier to read.

### CODE REVIEW

**Comment by eric-wieser** [comment]
real failure:
```
    def test_check_generalized_BAC_CAB_formulas(self):
    
        (a,b,c,d,e) = Ga('a b c d e').mv()
    
>       assert str(a|(b*c)) == '-(a.c)*b + (a.b)*c'
E       AssertionError: assert '(b.c)*a - (a.c)*b + (a.b)*c' == '-(a.c)*b + (a.b)*c'
E         - (b.c)*a - (a.c)*b + (a.b)*c
E         ? -------- -
E         + -(a.c)*b + (a.b)*c
```

**Comment by utensil** [comment]
So, should it actually be removed?

**Comment by eric-wieser** [comment]
I need to investigate this some more. Some of the failures are just addition reordering, which can be easily fixed.

The other half look like actual bugs. Leaving this as a draft for now, I probably need a piecewise approach to work out which bit is broken.

**Comment by eric-wieser** [comment]
Some timings:
```
In [2]: from galgebra.ga import Ga

In [3]: g, *a = Ga.build('e*1|2|3|4')

In [4]: A, B = g.mv('A', 'mv'), g.mv('B', 'mv')
```
Before:
```
In [5]: %timeit A < B
102 ms ± 2.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
After:
```
In [7]: %timeit A < B
105 ms ± 1.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

No significant change in the general case. Probably faster for a pure scalar contraction, but that doesn't seem like a case worth optimizing for.

**Pull request merged**
