### PR TITLE
Add `galgebra.__version__` for easy version inspection

### PR DESCRIPTION
**Pull request by eric-wieser**
This uses the same approach as clifford and pyganja

### CODE REVIEW

**Comment by utensil** [comment]
Can you change the sphinx conf too? Discussed in https://github.com/pygae/galgebra/pull/9#discussion_r262370967 .

**Comment by eric-wieser** [comment]
I couldn't find a version number in `conf.py`, otherwise I would have

**Comment by eric-wieser** [comment]
I think your `release` module is doing something magic there

**Comment by utensil** [comment]
Oh, seems I have delete the version line from sphinx sometime around introducing release. It's funny how my memory works. Looking for a closure without remembering the closure.

**Comment by eric-wieser** [comment]
Indeed, was removed in de366f81f36db13d871d78c9ca746b9afb7b2fcf

**Pull request merged**
