### PR TITLE
Small fixes to documentation

### PR DESCRIPTION
**Pull request by eric-wieser**
As an example, this page is now much easier to read:

https://galgebra--401.org.readthedocs.build/en/401/generated/galgebra.atoms.html#module-galgebra.atoms

### CODE REVIEW

**Comment by utensil** [comment]
image

**Comment by eric-wieser** [comment]
Yeah, I saw that too. I think I already have a sphinx bug open about this, I'll try to find it.

**Comment by utensil** [comment]
> I think I already have a sphinx bug open about this, I'll try to find it.

Have you found it? It seems to be coming out of nowhere, how could it leak inherited member like this......There seems to be no way around this from our end.

**Comment by eric-wieser** [comment]
There's an easy way around this, and it's to define:
```
def __init__(self, *args, **kwargs):
    """ """  # deliberately blank
    super().__init__(*args, **kwargs)
```

**Comment by eric-wieser** [comment]
I don't think I ever filed the issue. Essentially, sphinx gets unhappy when concatenating class-level and `__init__` - level docstrings.

**Pull request merged**
