### PR TITLE
Include the scalar element in the list of blades and bases

### LINKED ISSUE #64: Include the scalar in `Ga.blades_lst`, `Ga.indexes_lst`, and `Ga.bases_lst`
Opening this as a tracking issue so that I can reference it in the source code

### PR DESCRIPTION
**Pull request by eric-wieser**
~~The hope is this can eliminate a lot of special-casing of scalars~~

See commit message for details

Closes #64

### CODE REVIEW

**Comment by eric-wieser** [comment]
Expected this to fail, now to work out how extensively this breaks things

**Comment by eric-wieser** [comment]
@utensil asked on slack:

> Does any other GA library behave this way?

Yes, I did something like this as part of pygae/clifford#156

**Comment by utensil** [comment]
As I've stated in #83, this breaking change shall not be merged before the release of 0.4.5.

**Comment by eric-wieser** [comment]
Fair - I have a less intrusive change locally that doesn't affect the public API, which I'll put up for review shortly

**Comment by eric-wieser** [comment]
Conflicts resolved.

Coverage failure is caused by the fact this is a net loss of lines of code.

**Comment by eric-wieser** [comment]
I can think of one other option here, killing two birds with one stone.

* Deprecate `blades_lst`, leave it with the same meaning as before. The message can tell users to use `blades_list[1:]` instead.
* Add `blades_list` as the version that contains the scalar

**Comment by utensil** [comment]
@eric-wieser I totally agree with your solution.

**Comment by eric-wieser** [comment]
Updated to use the approach discussed on slack / above.

**Comment by utensil** [comment]
Generally, I feel OK with the nested approach since it's now clear that we should only have graded attributes with their flattened form, and this reduces the naming confusion.

But I wonder why to prefer `tuple` over `list` and am concerned with the mental compatibility.

**Pull request merged**
