### PR TITLE
Fix RecursionError when using sympy functions on Mv instances

### PR DESCRIPTION
**Pull request by eric-wieser**

### CODE REVIEW

**Comment by utensil** [comment]
Tests are failing?

**Comment by eric-wieser** [comment]
Needed some fixups, but works now

**Comment by utensil** [comment]
Now it seems to be more idiomatic to mix in the `CantSympify` trait like in https://github.com/TUD-RST/pycartan/blob/master/pycartan/core.py#L102

**Comment by eric-wieser** [comment]
Good find, but if we do that we lose our helpful error message.

**Comment by utensil** [comment]
Oh yes, let's keep it as is.

**Pull request merged**
