### PR TITLE
Improve the behavior of `galgebra.printer.oprint`

### PR DESCRIPTION
**Pull request by eric-wieser**
It's pretty clear this was the intended behavior, and it was just never tested / used enough to actually achieve it.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Note that right now this function only appears:

* Within debug code in `galgebra`
* In the `outdated` example folder

So we could consider deprecating it or making it private. It's possible we can also merge it with @abrombo's proposed `latex_print`

**Comment by utensil** [comment]
It's weird that ReviewNB didn't comment.

**Comment by utensil** [comment]
https://app.reviewnb.com/pygae/galgebra/pull/359/files/

**Comment by eric-wieser** [comment]
It looks like ReviewNB doesn't show whitespace properly anyway...

**Pull request merged**
