### PR TITLE
Do not clobber sympy.Basic.__str__

### PR DESCRIPTION
**Pull request by eric-wieser**
Instead we modify `print`, because at least nothing within sympy should be depending on that.

This fixes `simplify(expr)` behaving differently depending on whether latex printing was enabled or disabled when `simplify(expr)` was called for the _first_ time.
This is a horrible bug, and you could argue we deserved it for doing horrible things to sympy internals.

Ideally we would not replace `print` either, but that would be an API change, so should come as a future commit.

### CODE REVIEW

**Comment by asmeurer** [comment]
Can whatever you're doing here not be done with `init_printing`? Overriding a builtin seems even worse than monkeypatching SymPy, and doing it at import time is really bad.

**Comment by eric-wieser** [comment]
Everything here is terrible, this is just the minimal change needed to make it terrible in a way that doesn't cause more problems.

**Comment by utensil** [comment]
@eric-wieser Have you noticed @abrombo 's new printer design? We need to discuss further regarding the printer design and ensure that the design is consistent with SymPy's design.

Also please verify against https://github.com/utensil/julia-playground/blob/master/py/printing-galgebra.ipynb and https://github.com/utensil/julia-playground/blob/master/py/reproduce_new_printer_bug.ipynb as well.

**Comment by utensil** [comment]
And can you have a separate commit to reproduce "simplify(expr) behaving differently depending on whether latex printing was enabled or disabled when simplify(expr) was called for the first time" along with CI build demonstrating the unexpected results before fixing it?

**Comment by eric-wieser** [comment]
> And can you have a separate commit to reproduce "simplify(expr) behaving differently depending on whether latex printing was enabled or disabled when simplify(expr) was called for the first time.

It's awkward to write a test for this, because sympy caches the result. I'd need to do something like `subprocess.check_call([sys.executable, "with_latex.py"])`, and again without. I'll try to do that today

**Comment by eric-wieser** [comment]
> @eric-wieser Have you noticed @abrombo 's new printer design?

Yes. From what I could tell, it didn't touch anything outside of printer.py, so wasn't going to help with my issue. I don't think it will conflict heavily either though, so I still think we should put this in first (after I add some tests).

I'll try to split this up into some smaller PRs first.

**Comment by eric-wieser** [comment]
Split the non-controversial parts of this PR into #260 and #261. Only #260 is actually needed for this bugfix, and is now the first commit of this PR.

**Comment by eric-wieser** [comment]
Rebased upon #263, now that I merged that.

**Comment by eric-wieser** [comment]
Thanks @utensil for taking a look. Hopefully we can eventually change the printer to not patch builtins (`print`, `sys.stdout`) as @asmeurer suggests, but I fear doing so would be a breaking change.

**Comment by asmeurer** [comment]
To me monkeypatching a builtin, and at import time no less, is very bad behavior for a library. I would strongly encourage you to not do this.

**Comment by eric-wieser** [comment]
@asmeurer, we have some competing requirements here.

* The inherited `galgebra.printer` module disagrees with how sympy renders some things, and wants to render them differently through `print` by default. We want to preserve this.
* Sympy's symbolic manipulation is dependent on `Basic.__str__`. Modifying this at import time means that expressions pre- and post- import do not match.

Our choices are between:
1. Drop our attempt to override sympy display defaults at startup
2. Deal with inconsistent algebraic results that depend on import order
3. Monkey patch a built-in in an unobtrusive way

1 is the right approach in the long run, but is a "breaking" change. 2 was causing some very hard-to-debug behavior. 3 while being bad practice, is very unlikely to have any visible side-effect on users.

**Comment by eric-wieser** [comment]
In the long run, our approach should be:

* Monkey-patch the standard sympy printers to support our new types
* Create an opt-in subclass that contains the old opinionated overrides for your builtin types
* Add a registration function, that swaps out the `print` built-in to do essentially what this patch does now. Ideally no one will care enough about our tweaks to use it.

**Comment by asmeurer** [comment]
The SymPy printing system is designed to allow different kinds of printing. So I think if it doesn't support what you are trying to do we should see if it can be fixed in SymPy. Although I do vaguely remember not being able to change the default `__str__` on SymPy objects being an intentional design choice (but I could be wrong about that). 

For interactive use-cases, you can use `init_printing` to modify how the printing works. This modifies the `sys.displayhook` (not `print`), or in the case of Jupyter, the Jupyter printing system. These are both explicitly designed to be monkeypatched. You can make your own init_gaprinting() that makes this easier for users (similar to `init_vprinting` in the `sympy.physics.vector` module). 

For non-interactive cases, I would recommend users to use some sort of custom `gastr` function instead of `str` when converting objects to strings.

For objects that are galgebra objects, you can just define the str printing on them directly using `_latex` and `_sympystr` and so on. It sounds like you also want to change the printing of SymPy objects that don't necessarily involve galgebra objects (correct?). Can you explain what exactly the difference is with the monkeypatched printer?

**Comment by eric-wieser** [comment]
Thanks for the advice. I was looking for and could not find `_latex` and `_sympystr`, and am very pleased to discover they do exist after all :)

**Comment by eric-wieser** [comment]
> For interactive use-cases, you can use init_printing to modify how the printing works. This modifies the sys.displayhook (not print), or in the case of Jupyter, the Jupyter printing system. These are both explicitly designed to be monkeypatched. You can make your own init_gaprinting() that makes this easier for users (similar to init_vprinting in the sympy.physics.vector module). 

This sounds like a good idea. Unfortunately we still need to support patching `print` as an opt-in, as we have example code that majorly abuses `print`, as:

https://github.com/pygae/galgebra/blob/6c3856856ddcf1d5bbabe5f26b749c4bea85cca4/examples/LaTeX/Dop.py#L7-L34

The path forward there is probably to deprecate `Format`.

> It sounds like you also want to change the printing of SymPy objects that don't necessarily involve galgebra objects (correct?). Can you explain what exactly the difference is with the monkeypatched printer?

Yes, this is correct. From what I've seen so far, the changes are:

* Printing `Derivative(expr, x, 1, y, 2)` as `D{x}{y^2}(expr)`
* Handling symbol names differently, treating embedded `^` as `\wedge` instead of a superscript
* handling parentheses differently on `Pow`, maybe?

I don't really know for sure what else in there - @abrombo, it's original author may know more.

**Pull request merged**
