### PR TITLE
Change svg background color for dark mode

### PR DESCRIPTION
**Pull request by utensil**

### CODE REVIEW

**Comment by utensil** [comment]
Somehow this doesn't actually work yet, my guess is that the styles in tag `svg` has no effect or no precedence. PR it anyway to mark the issue:

In README:

image

In https://github.com/pygae/galgebra/blob/master/doc/module-components.rst#latex-printing :

image

**Comment by eric-wieser** [comment]
Is this just for the readme, or the Sphinx docs too?

**Comment by utensil** [comment]
Currently only for .md and .rst in Github Dark  theme .

**Comment by utensil** [comment]
https://github.com/StylishThemes/GitHub-Dark

**Comment by waldyrious** [comment]
> Somehow this doesn't actually work yet, my guess is that the styles in tag svg has no effect or no precedence.

What I usually do in these cases is create a rectangle for the background, with the same dimensions as the svg document/viewport. For example, for `Dop.svg`, that would be:

```diff
 </defs>
+<rect width="400" height="375" fill="#fcfcfc"/>
 <g id="surface1">
```

May I ask why use `rgb(252,252,252)` / `#fcfcfc` instead of plain white, though? That will make these slightly off in a white background.

Also, note that the contents of the SVG files are immediately adjacent to its margins, so a white fill would still not look good in a dark background. You'd need some sort of margin, e.g.:

```diff
 <?xml version="1.0" encoding="UTF-8"?>
-<svg ... width="400pt" height="375pt" viewBox="0 0 400 375" version="1.1">
+<svg ... width="400pt" height="375pt" viewBox="-10 10 420 395" version="1.1">
 <defs>
 ...
 </defs>
+<rect x="-10" y="-10" width="420" height="395" fill="#fcfcfc"/>
 <g id="surface1">
 ...
 </g>
 </svg>
```

**Comment by utensil** [comment]
> May I ask why use `rgb(252,252,252)` / `#fcfcfc` instead of plain white, though? That will make these slightly off in a white background.

Using `rgb(252,252,252)` / `#fcfcfc` is to match the background color of http://galgebra.readthedocs.io/.

**Comment by utensil** [comment]
> What I usually do in these cases is create a rectangle for the background, with the same dimensions as the svg document/viewport. For example, for `Dop.svg`, that would be:
> 
> ```diff
>  </defs>
> +<rect width="400" height="375" fill="#fcfcfc"/>
>  <g id="surface1">
> ```

Thanks for the suggestion. Why I'm hesitating is that this method is too manual, although not much of a trouble.

**Comment by eric-wieser** [comment]
Could alternatively fix this with https://github.com/StylishThemes/GitHub-Dark/issues/1060

**Comment by utensil** [comment]
`` gives:



which looks like this:

image

**Comment by eric-wieser** [comment]
Sounds like a bug you should report back to Github-Dark.

**Comment by utensil** [comment]
> Sounds like a bug you should report back to Github-Dark.

Indeed, will do that instead.

**Comment by utensil** [comment]
Related post: https://driesvints.com/blog/investigating-dark-mode-for-svgs-in-github-readmes

Latest official solution: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by utensil** [comment]
Superseded by #503

**Pull request closed without merging**
