### PR TITLE
Allow algebras with only 1 or even 0 basis vectors

### PR DESCRIPTION
**Pull request by eric-wieser**
Support for just one basis is needed for dual numbers, cc @tBuLi.

### CODE REVIEW

**Comment by eric-wieser** [comment]
CI failure is https://github.com/computationalmodelling/nbval/issues/139#issuecomment-665383149

**Comment by tBuLi** [comment]
Thanks for the quick PR!

**Comment by eric-wieser** [comment]
CI failure looks like an accidental upstream sympy change of my own making...

**Comment by utensil** [comment]
Why are there much more failure in this PR for sympy master?

**Comment by eric-wieser** [comment]
Because it needs rebasing on top of the other PR you just merged

**Comment by eric-wieser** [comment]
@tBuLi: If you want to use this before we next release (which could be quite a while), you can `pip install git+https://github.com/pygae/galgebra.git`

**Pull request merged**
